# docker-compose.yml
version: '2'
services:
  trucking-yang:
    container_name: trucking-yang
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    command: sh -c 'npm run start'
    restart: unless-stopped
    networks:
      - swag_network

networks:
  swag_network:
    external: true